### ISSUE TITLE
.exe

### ISSUE THREAD

**Issue by Anchovy8629** [trackirtoopentrack/trackir-to-opentrack#1]
@gpuandcpu Hello, could you explain what the .exe does exactly? Thanks.

**Comment by trackirtoopentrack** [comment]
@Anchovy8629 Hello, the program intercepts packets from TrackIR5 utility and converts them into OpenTrack coordinates. Thanks to OpenTrack filters, the use of the TrackIR device can be smoother in games like DCS.

**Comment by trackirtoopentrack** [comment]
Feel free to test trackir-to-opentrack utility. Small and fair donation grants you ability to to use it without any limitation.
We are opened for suggestions about the source code sharing. This will require a good justification.

**Comment by trackirtoopentrack** [comment]
I apologize, but the code is intellectual property and for this obvious reason will not be distributed. The executable file is suspicious because it lacks an official signature.

You have every right not to download it and not to recommend it to anyone. However, the program is so unique that it is quite difficult to find someone who really needs it.
